version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  api:
    build: ./api
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/no-good-trial
    depends_on:
      - mongodb
    networks:
      - app-network

  client:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./client/nginx-local.conf:/etc/nginx/conf.d/default.conf

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
